version: "3"
services:
#elastic search
  elasticsearch:
    image: elasticsearch:8.3.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: kibana:8.3.3
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
      ELASTICSEARCH_HOSTS: http://localhost:9200
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  logstash:
    container_name: logstash
    image: logstash:8.3.3
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #   logging:
  #     driver: "fluentd"
  #     options:
  #       fluentd-async-connect: "true"
  #       fluentd-address: localhost:24224
  #       tag: fluentd
  #   networks:
  #     - elasticsearch
  # fluentd:
  #   build: ./fluentd
  #   container_name: fluentd
  #   volumes:
  #     - ./fluentd/conf:/fluentd/etc
  #   ports:
  #     - "24224:24224"
  #     - "24224:24224/udp"
  #   networks:
  #     - elasticsearch
  # apm-server:
  #   image: elastic/apm-server:8.3.3
  #   container_name: apm-server
  #   volumes:
  #     - ./apm_elastic/apm-server.yml:/usr/share/apm-server/apm-server.yml
  #   environment:
  #     - output.elasticsearch.hosts=["localhost:9200"]
  #   ports:
  #     - "8200:8200"
  #   networks:
  #     - elasticsearch
volumes:
  elasticsearch-data:
    driver: local